# Generated by Django 5.0.2 on 2024-04-20 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipies_data',
            new_name='Recipe',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies_list_app.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
