# Generated by Django 5.0.2 on 2024-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies_list_app', '0003_rename_recipe_recipies_data_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='recipies_data',
            name='comments',
            field=models.ManyToManyField(related_name='recipies', to='recipies_list_app.comment'),
        ),
    ]
